#!/bin/bash
if [[ -f /etc/init.d/tomcat6 ]] ; then
    tomcatName=tomcat6
elif [[ -f /etc/init.d/tomcat7 ]] ; then
    tomcatName=tomcat7
fi
update-rc.d $tomcatName defaults
/etc/init.d/$tomcatName stop
rm -rf /var/lib/$tomcatName/webapps/MariaDBManager/
ln -s /usr/local/skysql/WebUI/MariaDBManager.war /var/lib/$tomcatName/webapps/MariaDBManager.war
chown -R ${tomcatName}:${tomcatName} /usr/local/skysql/WebUI/
chown ${tomcatName}:${tomcatName} /var/lib/$tomcatName/webapps/MariaDBManager.war
iptables -I INPUT -p tcp --dport 8080 -j ACCEPT
iptables-save > /etc/iptables/rules.v4
/usr/local/skysql/tmp/proxypass_debian.sh
rm -rf /usr/local/skysql/tmp/
/etc/init.d/$tomcatName restart
